configtxlator: http://192.168.1.151:7059
invokeWaitTime: 22000
proposalWaitTime: 22000
channelName: tid
deployWaitTime: 22000
orgs:
  'No':
    mspId: NoMSP
    contextUser:
      affiliation: ''
      name: Admin
    peerAdmin:
      affiliation: ''
      name: Admin
    domainName: no.com
    name: 'No'
    peers:
      peer3:
        anchor: false
        domainName: peer3.no.com
        roles: ledgerQuery,eventSource
        name: peer3
        location: grpcs://peer3.no.com:7051
      peer2:
        anchor: true
        domainName: peer2.no.com
        roles: ledgerQuery,serviceDiscovery,chaincodeQuery,endorsingPeer,eventSource
        name: peer2
        location: grpcs://peer2.no.com:7051
    admin:
      affiliation: ''
      name: Admin
    orderers: {}
    type: peer
    ca:
      name: ca-org2
      location: https://192.168.1.154:7054
  Dms:
    mspId: DmsMSP
    contextUser:
      affiliation: ''
      name: Admin
    peerAdmin:
      affiliation: ''
      name: Admin
    domainName: dms.com
    name: Dms
    peers:
      peer1:
        anchor: false
        domainName: peer1.dms.com
        roles: ledgerQuery,eventSource
        name: peer1
        location: grpcs://peer1.dms.com:7051
      peer0:
        anchor: true
        domainName: peer0.dms.com
        roles: ledgerQuery,serviceDiscovery,chaincodeQuery,endorsingPeer,eventSource
        name: peer0
        location: grpcs://peer0.dms.com:7051
    admin:
      affiliation: ''
      name: Admin
    orderers: {}
    type: peer
    ca:
      name: ca-org1
      location: https://192.168.1.152:7054
  Orderer:
    mspId: OrdererMSP
    contextUser:
      affiliation: ''
      name: Admin
    peerAdmin:
      affiliation: ''
      name: Admin
    domainName: cid.com
    name: Orderer
    peers: {}
    admin:
      affiliation: ''
      name: Admin
    orderers:
      orderer:
        domainName: orderer.cid.com
        name: orderer
        location: grpcs://orderer.cid.com:7050
    type: orderer
channelPath: ''
clientOrgName: Dms
