#存证合约配置
chaincodeDir: chaincode/gocc/cid/
chaincodePath: dm.com/cid_cc/
chaincodeVersion: 1.0
chaincodeLang: GO_LANG
#invokeWaitTime: 120000   #交易（即执行合约操作）等待时间，若没有配置，则提前面配置的全局时间
#deployWaitTime: 120000   #实例化等待时间，若没有配置，则提前面配置的全局时间
#proposalWaitTime: 120000  #交易提案等待时间，若没有配置，则提前面配置的全局时间
endorseCount: 1    #最少背书数量，根据背书策略定义进行配置，只有满足最少背书数量，才能提交给Orderer，否则提交也没意义
endorsePeers:      #指定已安装合约的背书节点，不指定则交易发送给channel上所有已安装合约的背书节点
#- peer0.org1.example.com:7051
#- peer0.org2.example.com:9051
endorsePolicyPath: chaincode/policy/cid/chaincodeendorsementpolicy.yaml