#application通用环境配置
spring:
   freemarker:
     checkTemplateLocation: false
   mvc:
      date-format: yyyy-MM-dd HH:mm:ss
      #spring-webmvc的视图解析
      #view:
      #prefix: /WEB-INF/
      #suffix: .jsp
      # 静态文件请求匹配方式
      static-path-pattern: /**
   #jackson:  
      #date-format: yyyy-MM-dd HH:mm:ss
      #serialization: 
         #WRITE_ENUMS_USING_INDEX: true
         #FAIL_ON_EMPTY_BEANS: false
   messages:
      #国际化语言配置，表示放在classpath的i18n文件夹，文件前缀为msg  
      #cacheSeconds：加载国际化文件的缓存时间，单位为秒，默认为永久缓存。
      encoding: UTF-8
      basename: i18n/msg   #相对路径 首部请勿添加斜杠,可以通过逗号指定多个,application.properties写法i18n.msg
   #dev tools 热部署
   devtools:
      livereload:
         enabled: true
   servlet:
     multipart:
       enabled: false
       resolve-lazily: true
   jpa:
     open-in-view: false
   thymeleaf:
     enabled: false
     check-template-location: false
#log配置
logging:
   config: classpath:config/log4j2.xml
#logging.level=info
#logging.level.com.sc=debug

#security配置
security:
  #basic:
  #  enabled: false
  token:
     secret: dm@123@dm     #token加密的服务端密钥，不能泄漏，否则客户端可以自己生成token
     expiredTime: 360000000    #过期时间，单位毫秒，即多少毫秒后过期
     requestParameter: Authorization     #url请求上传token的参数名称，默认为Authorization
     prefix: Bearer          #url请求上传的token值前缀，验证时需要去掉此前缀         
  passwordEncoder: MD5       #密码编码器，默认使用BCrypt密码编码器
  login:
     usernameParameter: username   #spring security登录用户名参数名称，默认为username
     passwordParameter: password   #spring security登录密码参数名称，默认为password
management:
  security:
    enabled: false

swagger:
  #enable: false   #开关，是否启用swagger
  title: iMark API  #标题
  desc: 接口描述   #描述
  termsOfServiceUrl: http://localhost  #服务条款
  version: 1.0.0   #接口版本
  license: licese  #许可证名称
  licenseUrl: http://localhost   #许可证地址
  basePackage: com.dm # 扫描的基础包
  token: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxODgxMjM0NTY3OCIsImV4cCI6MTU2OTU2NzYwNCwidXNlcmlkIjoiNzAiLCJpYXQiOjE1NjkyMDc2MDR9.hZTmo2ToI2na0SHwZ7l54RUg9vChcoiDX-wXA6XXaquvOCBY5qEX2ReGALNtYTkzsyt1d2VhCgvTQgTzavulhA   #登录后获取的token，也就是需要先启动登录后，把token赋值到这，再重新启动，只为测试使用。