#application开发环境配置
server:
   port: 8080    #不指定默认为8080
spring:
   profiles:
      #配置扩展profiles
      include: sys,mybatis,socket,devDS,devRedis,common

upload:
   filePath: D:\upload\cert
   filePrefix: http://192.168.3.101/img/cert
#邮箱设置
email:
  address: 18811012959@163.com
  smtp: smtp.163.com
  pwd: jq390813
  subject: 【迪曼森】
  emailContent: 【存证平台】您的验证码是：$code$，验证码五分钟内有效，请不要把验证码泄露给其他人。
  expired: 300000 #毫秒
#极光推送服务
jpush:
  appKey: f0e7dec1b2aefc534e08fe18
  masterSecret: 2464890880bcd3f52e00c1d7

