# application开发环境配置
server:
  # 不指定默认为8080
  port: 9080
spring:
  profiles:
    # 配置扩展 profiles 文件
    include: sys,mybatis,socket,proDS,common
upload:
  # 存证文件存储路径
  certFilePath: /opt/czt-upload/certfile
  # 存证文件访问路径
  certFilePrefix: http://114.244.37.10:7080/img/certfile
  # 出证文件存储路径
  outCertFilePath: /opt/czt-upload/outcert/file
  # 出证文件访问下载路径
  outCertFilePrefix: http://114.244.37.10:7080/img/outcert/file
  # 用户头像存储路径
  headFilePath: /opt/czt-upload/headfile
  # 用户头像访问路径
  headFilePrefix: http://114.244.37.10:7080/img/headfile
# 邮箱设置
email:
  # 发送人邮箱地址
  address: 18811012959@163.com
  # 发送人邮箱smtp
  smtp: smtp.163.com
  # 发送人邮箱授权码
  pwd: jq390813
  # 邮箱主题
  subject: 【迪曼森】
  # 邮箱发送内容
  emailContent: 【iMark】您的验证码是：$code$，验证码五分钟内有效，请勿提供给他人可能导致账号被盗。请勿泄露，谨防被骗。
  # 邮件过期时间 (单位毫秒)
  expired: 300000
# 极光推送服务
jpush:
  # 极光推送 appKey
  appKey: f0e7dec1b2aefc534e08fe18
  # 极光推送 秘钥
  masterSecret: 2464890880bcd3f52e00c1d7
