#当前Channel配置
name: cid
path: classpath:channel/cid/    #src/main/resources/
store: cidStore.properties
configtxlatorLocation: http://192.168.1.202:7059
tls: true
invokeWaitTime: 32000
deployWaitTime: 120000
proposalWaitTime: 120000
clientOrg: org1
orgs:
  org1:
    mspId: Org1MSP
    domainName: org1.example.com
    type: peer
    ca:
      name: ca_peerOrg1    #要跟区块链网络上部署的CA容器名称一致
      location: http://192.168.1.202:7054
    orderers:
      orderer:
        domainName: orderer.example.com
        location: grpc://192.168.1.202:7050
    peers:
      peer0:
        domainName: peer0.org1.example.com
        location: grpc://192.168.1.202:7051
        roles: ledgerQuery,chaincodeQuery,endorsingPeer,eventSource,serviceDiscovery  #endorsingPeer/chaincodeQuery/ledgerQuery/eventSource/serviceDiscovery/all/no_event_source
      peer1:
        domainName: peer1.org1.example.com
        location: grpc://192.168.1.202:8051
        roles: ledgerQuery,eventSource  #endorsingPeer/chaincodeQuery/ledgerQuery/eventSource/serviceDiscovery/all/no_event_source
    admin:
      name: Admin
    peerAdmin:
      name: Admin
  org2:
    mspId: Org2MSP
    domainName: org2.example.com
    type: peer
    ca:
      name: ca_peerOrg2    #要跟区块链网络上部署的CA容器名称一致
      location: http://192.168.1.202:8054
    orderers:
      orderer:
        domainName: orderer.example.com
        location: grpc://192.168.1.202:7050
    peers:
      peer0:
        domainName: peer0.org2.example.com
        location: grpc://192.168.1.202:9051
        roles: ledgerQuery,chaincodeQuery,endorsingPeer,eventSource,serviceDiscovery  #endorsingPeer/chaincodeQuery/ledgerQuery/eventSource/serviceDiscovery/all/no_event_source
      peer1:
        domainName: peer1.org2.example.com
        location: grpc://192.168.1.202:10051
        roles: ledgerQuery,eventSource  #endorsingPeer/chaincodeQuery/ledgerQuery/eventSource/serviceDiscovery/all/no_event_source
    admin:
      name: Admin
    peerAdmin:
      name: Admin
anchorPeers:    #锚节点，也称为定位节点，实现与其它组织节点之间互通
  - peer0.org1.example.com:7051
  - peer0.org2.example.com:9051
chaincodes:
  cid_cc:
    chaincodeDir: chaincode/gocc/cid/
    chaincodePath: dm.com/cid_cc/
    chaincodeVersion: 1.6
    chaincodeLang: GO_LANG