#存储Channel配置
channelName: cid
configtxlator: http://192.168.1.202:7059
invokeWaitTime: 32000
deployWaitTime: 120000
proposalWaitTime: 120000
clientOrgName: org1
orgs:
  Orderer:
    mspId: OrdererMSP
    domainName: example.com
    type: orderer
    orderers:
      orderer:
        domainName: orderer.example.com
        location: grpcs://orderer.example.com:7050   #如果是TLS，则配置为grpcs://
    contextUser:     #会话用户，主要负责客户端上下会话，即客户端用户，代表客户端
      name: Admin
    #admin:
    #  name: Admin
    #peerAdmin:
      #name: Admin
  org1:
    mspId: Org1MSP
    domainName: org1.example.com
    type: peer
    ca:
      name: ca_peerOrg1    #要跟区块链网络上部署的CA容器名称一致
      location: https://192.168.1.202:7054
    peers:
      peer0:
        domainName: peer0.org1.example.com
        location: grpcs://peer0.org1.example.com:7051
        roles: ledgerQuery,chaincodeQuery,endorsingPeer,eventSource,serviceDiscovery  #endorsingPeer/chaincodeQuery/ledgerQuery/eventSource/serviceDiscovery/all/no_event_source
        anchor: true   #是否为锚节点，也称为定位节点，实现与其它组织节点之间互通
      peer1:
        domainName: peer1.org1.example.com
        location: grpcs://peer1.org1.example.com:8051
        roles: ledgerQuery,eventSource  #endorsingPeer/chaincodeQuery/ledgerQuery/eventSource/serviceDiscovery/all/no_event_source
    contextUser:     #会话用户，主要负责客户端上下会话，即客户端用户，代表客户端
      name: Admin
    admin:
      name: Admin
    peerAdmin:
      name: Admin
  org2:
    mspId: Org2MSP
    domainName: org2.example.com
    type: peer
    ca:
      name: ca_peerOrg2    #要跟区块链网络上部署的CA容器名称一致
      location: https://192.168.1.202:8054
    peers:
      peer0:
        domainName: peer0.org2.example.com
        location: grpcs://peer0.org2.example.com:9051
        roles: ledgerQuery,chaincodeQuery,endorsingPeer,eventSource,serviceDiscovery  #endorsingPeer/chaincodeQuery/ledgerQuery/eventSource/serviceDiscovery/all/no_event_source
        anchor: true   #是否为锚节点，也称为定位节点，实现与其它组织节点之间互通
      peer1:
        domainName: peer1.org2.example.com
        location: grpcs://peer1.org2.example.com:10051
        roles: ledgerQuery,eventSource  #endorsingPeer/chaincodeQuery/ledgerQuery/eventSource/serviceDiscovery/all/no_event_source
    contextUser:     #会话用户，主要负责客户端上下会话，即客户端用户，代表客户端
      name: Admin
    admin:
      name: Admin
    peerAdmin:
      name: Admin