#当前Channel配置
name: cid
path: classpath:channel/cid/
store: cidStore.properties
configtxlatorLocation: http://192.168.1.202:7059
tls: true
invokeWaitTime: 32000
deployWaitTime: 120000
proposalWaitTime: 120000
clientOrg: org1
orgs:
  org1:
    mspId: Org1MSP
    domainName: org1.example.com
    caLocation: http://192.168.1.202:7054
    caName: ca0
    peerLocations:
      peer0.org1.example.com: grpc://192.168.1.202:7051
      peer1.org1.example.com: grpc://192.168.1.202:8051
    ordererLocations:
      orderer.example.com: grpc://192.168.1.202:7050
    admin:
      name: Admin
      enrollmentSecret: adminpw
    peerAdmin:
      name: Admin
      enrollmentSecret: adminpw
peerRoles:          #endorsingPeer/chaincodeQuery/ledgerQuery/eventSource/serviceDiscovery/all/no_event_source
  peer0.org1.example.com: ledgerQuery,chaincodeQuery,endorsingPeer,eventSource
  peer1.org1.example.com: ledgerQuery,chaincodeQuery,endorsingPeer,eventSource
chaincodes:
  cid_cc:
    chaincodeDir: chaincode/gocc/cid/
    chaincodePath: dm.com/cid_cc/
    chaincodeVersion: 1.0
    chaincodeLang: GO_LANG