chaincodePath: github.com/tid_cc/
invokeWaitTime: 22000
proposalWaitTime: 22000
endorseCount: 1
chaincodeLang: GO_LANG
chaincodeDir: chaincode/gocc/tid_cc/
endorsePolicyPath: chaincode/policy/tid_cc/chaincodeendorsementpolicy.yaml
chaincodeVersion: '1.3'
deployWaitTime: 22000
endorsePeers: []
chaincodeName: tid_cc
