NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.dev.no.com-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.dev.no.com-cert.pem
    OrganizationalUnitIdentifier: peer
